baseURL = "https://joemattiello.dev/"
languageCode = "en-us"
title = "Joe Mattiello"
theme = "hugo-resume"
disableKinds = [ "taxonomy", "taxonomyTerm"]

[params]
    firstName = "Joseph"
    lastName = "Mattiello"
    address = "New York, NY"
    phone = "1-646-771-8604"
    contactNote = "iOS Engineer"
    profileImage = "img/twitter.jpg"
    email = "mail@joemattiello.com"
    description = "iOS Platform Engineer with experience leveraging Swift, MVVM, Rx, agile, DevOps, and CI/CD to manage large scale mobile applications."
    favicon = "/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/joemattiello/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/JoeMatt/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/story/joemattiello"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/jmattiello"
    icon = "keybase"

[params.google.analytics]
    trackerID = "UA-5727797-5"
